apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
     app: mongo 
spec:
  volumes:
    - name: "mongodb-data"
      hostPath:
        path: /tmp/mongodb
  containers:
    - image: docker.io/mongo:latest
      name: mongodb
      volumeMounts:
        - mountPath: "/data/db"
          name: "mongodb-data"
      ports:
        - containerPort: 27017
          name: socket
          protocol: TCP
