apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tasks
  name: tasksapi
spec:
  containers:
    - image: docker.io/jmhal/tasks:1.3
      name: api
      ports:
        - containerPort: 10000
          name: http
          protocol: TCP
