apiVersion: v1
kind: Service
metadata:
  name: tasksservice
spec:
  ports:
    - nodePort: 30001
      port: 8001
      protocol: TCP
      targetPort: 10000
  selector:
    app: tasks
  type: NodePort
